### ISSUE TITLE
"The website encountered an unexpected error" after last step of installation

### ISSUE THREAD

**Issue by klonos** [PackWeb/pw_profile#5]
Hey @BWpanda 👋

...I tried the following:

- `git clone https://github.com/backdrop/backdrop`
- manually downloaded the latest from https://github.com/PackWeb/pw_profile
- created a `/profiles` folder in webroot
- extracted `pw_profile` in `/profiles/pw_profile`

(at this point, I had not merged any of the changes from https://github.com/backdrop/backdrop/pull/2784)

- started the installer -> I saw a "select profile" step 👍
- clicking next on the installer skipped the profile selection page. I imagine that this is OK, since only one profile was available, and it seems that you have set `exclusive = TRUE` in the .info 👍 (https://github.com/PackWeb/pw_profile/blob/master/pw_profile.info#L4)
- the progress in the "Installing Backdrop CMS" step mentioned having installed the PackWeb *module* (instead of saying "profile" - known issue though: https://github.com/backdrop/backdrop-issues/issues/3796) 
- reaching the site info entry page, I saw the site name set to `PackWeb` and the email set to `info@packweb.eu`, so I assumed all was good 👍
- clicking next got me to this screen:

<img width="723" alt="Screen Shot 2019-07-10 at 7 02 11 am" src="https://user-images.githubusercontent.com/2423362/60922704-a9ffd300-a2e0-11e9-9912-f62c6b82cd2a.png">

I plan to start from scratch, having error logging enabled, to see if that gives me any clue, but wanted to check with you in case this is a known issue.

**Comment by BWPanda** [comment]
The majority of the code in the profile is for setting up and configuring the various modules used. Unfortunately I don't think Drush Make is quite working the way I'd need it to, so there's currently no automated way of getting all the modules you need. You'll have to look through the code to get the list of modules and download them manually. I'm assuming that's why the error...

**Comment by BWPanda** [comment]
Actually there is a make file, but not sure if it works. It at least lists the modules you need: https://github.com/PackWeb/pw_profile/blob/master/pw_profile.make

**Comment by klonos** [comment]
Thanks @BWPanda ...did not think of that, but makes sense.

Curious why you are not using `dependencies[]` in the .info file though? ...I'm assuming that in that case, there would be an error during installation, to give me a clue about missing modules.

**Comment by klonos** [comment]
...also curious to see if core is able to automatically download those dependencies if internet connection is available.

**Comment by BWPanda** [comment]
I believe there was an issue with dependencies not getting installed in the correct order... Very long time ago though, so can't quite remember exactly.

**Comment by klonos** [comment]
You may have noticed that now that I started digging into this, I have filed some issues against core. https://github.com/backdrop/backdrop-issues/issues/3923 https://github.com/backdrop/backdrop-issues/issues/3924

>I believe there was an issue with dependencies not getting installed in the correct order.

I imagine you are referring to "nested" dependencies. Intriguing 🤔

**Comment by klonos** [comment]
...adding things in the .info file as dependencies makes it so that there is a proper missing requirements error during the installer. That way, users will not get this "cryptic" error at the end of a seemingly successful installation: https://github.com/PackWeb/pw_profile/pull/6

**Comment by klonos** [comment]
I have now dowloaded all required modules, and extracted them to `/modules`. The installer now used a themed site configuration screen:

<img width="645" alt="Screen Shot 2019-07-11 at 4 12 58 am" src="https://user-images.githubusercontent.com/2423362/60993635-31594f00-a392-11e9-958b-7ae5f6513b47.png">

...and got me straight into maintenance mode:

<img width="659" alt="Screen Shot 2019-07-11 at 4 10 18 am" src="https://user-images.githubusercontent.com/2423362/60993643-34ecd600-a392-11e9-9e80-f8a314b3c512.png">

I will need to enable error logging and test again.

**Comment by BWPanda** [comment]
The maintenance page issue is because of https://github.com/backdrop-contrib/maintenance_page and I filed https://github.com/backdrop/backdrop-issues/issues/3175 as a result...

**Comment by klonos** [comment]
Gotcha 👍 ...I had forgotten about that one.

**Comment by BWPanda** [comment]
Fixed the maintenance page thing: https://github.com/backdrop-contrib/maintenance_page/commit/3426a766684a3d772a1df83d194cfe9fc56b0a94 New release available too.

**Comment by BWPanda** [comment]
I won't be inplementing this. See https://github.com/PackWeb/pw_profile/pull/6#issuecomment-635889120 for reasons why.
